version: "3"
services:
  # Jaeger for tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      #- 6831:6831/udp
      #- 6832:6832/udp
      #- 14268:14268
      - 16686:16686
      - 4317:4317
      - 4318:4318
